name: Build README.md

on:
  push:
    branches:
      - develop

env:
  RELEASE_BRANCH: main

permissions:
  contents: write
  repository-projects: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          ref: develop
          path: ./develop

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: ./main

      - name: Build README.md
        run: ./build.sh
        working-directory: ./develop

      - name: Copy README.md to main branch
        run: |
          cp ./develop/out/README.md ./main
          cp -r ./develop/assets ./main

      - name: Commit and push
        id: commit_and_push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "Working directory clean. Nothing to commit."
            echo "NO_CHANGES=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          git commit -m "feat: update README.md [skip ci]"
          git push --force origin main
        working-directory: ./main
