name: Build README.md

on:
  push:
    branches:
      - develop

env:
  RELEASE_BRANCH: main

permissions:
  contents: write
  repository-projects: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          ref: develop
          path: ./

      - name: Build README.md
        run: ./build.sh

      - name: Git setup
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          release_branch=${{ env.RELEASE_BRANCH }}
          git fetch origin $release_branch
          git branch $release_branch origin/$release_branch
          git checkout $release_branch

      - name: Commit and push
        id: commit_and_push
        run: |
          git add README.md
          if [ -z "$(git status --porcelain)" ]; then
            echo "Working directory clean. Nothing to commit."
            echo "NO_CHANGES=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          git commit -m "feat: update README.md [skip ci]"
          git push --force origin ${{ env.RELEASE_BRANCH }}
